SPACE script-message mira-pause
k script-message mira-pause
MBTN_LEFT script-message mira-pause
MBTN_LEFT_DBL script-message mira-fullscreen
MOUSE_MOVE script-message mira-motion
LEFT script-message mira-seek-back
RIGHT script-message mira-seek-forward
UP script-message mira-volume-up
DOWN script-message mira-volume-down
m script-message mira-mute
f script-message mira-fullscreen
i script-message mira-mini
s script-message mira-skip
ESC script-message mira-back
j cycle sub
SHARP cycle audio
